version: "3.2"
services:
  elasticsearch:
    build: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./data/es01
        target: /usr/share/elasticsearch/data
        read_only: false
    ports:
      - 9200:9200
    networks:
      - elk_stack

  kibana:
    build: kibana
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk_stack
    depends_on:
      - elasticsearch

  apm:
    build: apm
    volumes:
      - type: bind
        source: ./apm/config/apm-server.docker.yml
        target: /usr/share/apm-server/apm-server.yml
        read_only: true
    ports:
      - "8200:8200"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk_stack
    depends_on:
      - elasticsearch
      - kibana

  logstash:
    build: logstash
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk_stack
    depends_on:
      - elasticsearch
      - kibana

  filebeat:
    build: filebeat
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.docker.yml
        target: /usr/share/filebeat/config/filebeat.yml
        read_only: true
      - type: bind
        source: ./data/logs/nginx
        target: /var/log/nginx
        read_only: true
    networks:
      - elk_stack
    depends_on:
      - elasticsearch
      - kibana
      - logstash
#    setup: filebeat setup -e -E output.logstash.enabled=enable -E output.elasticsearch.hosts=['elasticsearch:9200'] -E setup.kibana.host=kibana:5601 -E setup.

networks:
  elk_stack:
    driver: bridge
